server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""   # <- vide si pas de mot de passe root, sinon mets-le ici
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: "this-is-a-very-long-random-secret-key-at-least-32-chars"
  expiration: 3600000   # 1h en millisecondes
